### ISSUE TITLE
[No rule to make target 'fortran/COMMONS.f',needed by 'src/PASS_FTN_ALT.f'. Stop]

### ISSUE THREAD

**Issue by spiekel** [jowr/librefprop.so#22]
Merry Christmass!

I tried to install the shared library with Refprop 9.0 on a 10.10.1 Mac OS X system. 

For the purpose I followed the instructions provided on : 

https://github.com/jowr/librefprop.so

and I used GCC4.2.1 and gfortran 4.8.2.

however, during the sudo make install I run into the following problem : 

make: *** No rule to make target  fortran/COMMONS.f', needed by src/PASS_FTN_ALT.f'. Stop. 

I found that I don't have the COMMONS.f from my fortran directory in REFPROP\fortran. 

Where can I find this COMMONS.f file?

With Kind Regards,

Choi

**Comment by bo3mrh** [comment]
v0.2 works fine with me on REFPROP 9.0. I'm working on OSX 10.10.2, GCC 4.2.1 and gfortran 4.9.2

**Comment by jowr** [comment]
Thank you for the feedback @bo3mrh . I guess we can close this now.
