### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by jaabarreto** [jowr/librefprop.so#30]
Does it works for REFPROP 8.0? When I try to make this error appears:

No rule to make target `fortran/COMMONS.f', needed by `src/PASS_FTN_ALT.f'.

**Comment by jowr** [comment]
Hi, I have never tested it with anything below 9.0, but v0.2 from https://github.com/jowr/librefprop.so/releases is the last one that works with 9.0 - it might also work for you.

**Comment by jaabarreto** [comment]
I got this error

gfortran  -Wall -pedantic  -o ./src/PASS_FTN_LIN.o -c src/PASS_FTN_LIN.FOR
make: gfortran: No such file or directory
make: *** [src/PASS_FTN_LIN.o] Error 1

**Comment by jowr** [comment]
Hm, looks like REFPROP 8.0 has different files than REFPROP 9.0. Could you post a listing of the source directory?

**Comment by jaabarreto** [comment]
fluids:
-rwx------  1 jorgebarreto1  staff    7381 10 Abr  2007 1BUTENE.FLD
-rwx------  1 jorgebarreto1  staff    5655 10 Abr  2007 ACETONE.FLD
-rwx------  1 jorgebarreto1  staff   22434 10 Abr  2007 AIR.PPF
-rwx------  1 jorgebarreto1  staff   23960 10 Abr  2007 AMMONIA.FLD
-rwx------  1 jorgebarreto1  staff   43126 10 Abr  2007 ARGON.FLD
-rwx------  1 jorgebarreto1  staff    5743 10 Abr  2007 BENZENE.FLD
-rwx------  1 jorgebarreto1  staff   41688 10 Abr  2007 BUTANE.FLD
-rwx------  1 jorgebarreto1  staff   19728 10 Abr  2007 C12.FLD
-rwx------  1 jorgebarreto1  staff    5914 10 Abr  2007 C2BUTENE.FLD
-rwx------  1 jorgebarreto1  staff    4461 10 Abr  2007 C4F10.FLD
-rwx------  1 jorgebarreto1  staff    4559 10 Abr  2007 C5F12.FLD
-rwx------  1 jorgebarreto1  staff    9363 10 Abr  2007 CF3I.FLD
-rwx------  1 jorgebarreto1  staff   18048 10 Abr  2007 CO.FLD
-rwx------  1 jorgebarreto1  staff   34278 10 Abr  2007 CO2.FLD
-rwx------  1 jorgebarreto1  staff    5385 10 Abr  2007 COS.FLD
-rwx------  1 jorgebarreto1  staff   12734 10 Abr  2007 CYCLOHEX.FLD
-rwx------  1 jorgebarreto1  staff    4535 10 Abr  2007 CYCLOPRO.FLD
-rwx------  1 jorgebarreto1  staff    5591 10 Abr  2007 D2.FLD
-rwx------  1 jorgebarreto1  staff   13390 10 Abr  2007 D2O.FLD
-rwx------  1 jorgebarreto1  staff   17458 10 Abr  2007 DECANE.FLD
-rwx------  1 jorgebarreto1  staff   12881 10 Abr  2007 DME.FLD
-rwx------  1 jorgebarreto1  staff   37055 10 Abr  2007 ETHANE.FLD
-rwx------  1 jorgebarreto1  staff   22607 10 Abr  2007 ETHANOL.FLD
-rwx------  1 jorgebarreto1  staff   27108 10 Abr  2007 ETHYLENE.FLD
-rwx------  1 jorgebarreto1  staff   10715 10 Abr  2007 FLUORINE.FLD
-rwx------  1 jorgebarreto1  staff   23881 10 Abr  2007 H2S.FLD
-rwx------  1 jorgebarreto1  staff   15163 10 Abr  2007 HELIUM.FLD
-rwx------  1 jorgebarreto1  staff   21947 10 Abr  2007 HEPTANE.FLD
-rwx------  1 jorgebarreto1  staff   22163 10 Abr  2007 HEXANE.FLD
-rwx------  1 jorgebarreto1  staff  144241 10 Abr  2007 HMX.BNC
-rwx------  1 jorgebarreto1  staff   23007 10 Abr  2007 HYDROGEN.FLD
-rwx------  1 jorgebarreto1  staff    6766 10 Abr  2007 IBUTENE.FLD
-rwx------  1 jorgebarreto1  staff   12090 10 Abr  2007 IHEXANE.FLD
-rwx------  1 jorgebarreto1  staff   23849 10 Abr  2007 IPENTANE.FLD
-rwx------  1 jorgebarreto1  staff   39602 10 Abr  2007 ISOBUTAN.FLD
-rwx------  1 jorgebarreto1  staff   13813 10 Abr  2007 KRYPTON.FLD
-rwx------  1 jorgebarreto1  staff   38862 10 Abr  2007 METHANE.FLD
-rwx------  1 jorgebarreto1  staff   19069 10 Abr  2007 METHANOL.FLD
-rwx------  1 jorgebarreto1  staff    7931 10 Abr  2007 N2O.FLD
-rwx------  1 jorgebarreto1  staff   10366 10 Abr  2007 NEON.FLD
-rwx------  1 jorgebarreto1  staff   10408 10 Abr  2007 NEOPENTN.FLD
-rwx------  1 jorgebarreto1  staff    5407 10 Abr  2007 NF3.FLD
-rwx------  1 jorgebarreto1  staff   44188 10 Abr  2007 NITROGEN.FLD
-rwx------  1 jorgebarreto1  staff   16969 10 Abr  2007 NONANE.FLD
-rwx------  1 jorgebarreto1  staff   27061 10 Abr  2007 OCTANE.FLD
-rwx------  1 jorgebarreto1  staff   38864 10 Abr  2007 OXYGEN.FLD
-rwx------  1 jorgebarreto1  staff   17080 10 Abr  2007 PARAHYD.FLD
-rwx------  1 jorgebarreto1  staff   22759 10 Abr  2007 PENTANE.FLD
-rwx------  1 jorgebarreto1  staff   44144 10 Abr  2007 PROPANE.FLD
-rwx------  1 jorgebarreto1  staff   16951 10 Abr  2007 PROPYLEN.FLD
-rwx------  1 jorgebarreto1  staff    5656 10 Abr  2007 PROPYNE.FLD
-rwx------  1 jorgebarreto1  staff   15527 10 Abr  2007 R11.FLD
-rwx------  1 jorgebarreto1  staff   11096 10 Abr  2007 R113.FLD
-rwx------  1 jorgebarreto1  staff    8172 10 Abr  2007 R114.FLD
-rwx------  1 jorgebarreto1  staff   17152 10 Abr  2007 R115.FLD
-rwx------  1 jorgebarreto1  staff   15762 10 Abr  2007 R116.FLD
-rwx------  1 jorgebarreto1  staff   13337 10 Abr  2007 R12.FLD
-rwx------  1 jorgebarreto1  staff   20089 10 Abr  2007 R123.FLD
-rwx------  1 jorgebarreto1  staff   15427 10 Abr  2007 R124.FLD
-rwx------  1 jorgebarreto1  staff   43371 10 Abr  2007 R125.FLD
-rwx------  1 jorgebarreto1  staff   17893 10 Abr  2007 R13.FLD
-rwx------  1 jorgebarreto1  staff   35372 10 Abr  2007 R134A.FLD
-rwx------  1 jorgebarreto1  staff   14276 10 Abr  2007 R14.FLD
-rwx------  1 jorgebarreto1  staff   12771 10 Abr  2007 R141B.FLD
-rwx------  1 jorgebarreto1  staff   11646 10 Abr  2007 R142B.FLD
-rwx------  1 jorgebarreto1  staff   19512 10 Abr  2007 R143A.FLD
-rwx------  1 jorgebarreto1  staff   27435 10 Abr  2007 R152A.FLD
-rwx------  1 jorgebarreto1  staff    5229 10 Abr  2007 R21.FLD
-rwx------  1 jorgebarreto1  staff   14289 10 Abr  2007 R218.FLD
-rwx------  1 jorgebarreto1  staff   18512 10 Abr  2007 R22.FLD
-rwx------  1 jorgebarreto1  staff   14059 10 Abr  2007 R227EA.FLD
-rwx------  1 jorgebarreto1  staff   23667 10 Abr  2007 R23.FLD
-rwx------  1 jorgebarreto1  staff   10275 10 Abr  2007 R236EA.FLD
-rwx------  1 jorgebarreto1  staff   10311 10 Abr  2007 R236FA.FLD
-rwx------  1 jorgebarreto1  staff   10842 10 Abr  2007 R245CA.FLD
-rwx------  1 jorgebarreto1  staff   16704 10 Abr  2007 R245FA.FLD
-rwx------  1 jorgebarreto1  staff   25998 10 Abr  2007 R32.FLD
-rwx------  1 jorgebarreto1  staff    6893 10 Abr  2007 R365MFC.FLD
-rwx------  1 jorgebarreto1  staff    6225 10 Abr  2007 R404A.PPF
-rwx------  1 jorgebarreto1  staff    6161 10 Abr  2007 R407C.PPF
-rwx------  1 jorgebarreto1  staff   18477 10 Abr  2007 R41.FLD
-rwx------  1 jorgebarreto1  staff    6182 10 Abr  2007 R410A.PPF
-rwx------  1 jorgebarreto1  staff    6191 10 Abr  2007 R507A.PPF
-rwx------  1 jorgebarreto1  staff   11194 10 Abr  2007 RC318.FLD
-rwx------  1 jorgebarreto1  staff   16047 10 Abr  2007 SF6.FLD
-rwx------  1 jorgebarreto1  staff    9075 10 Abr  2007 SO2.FLD
-rwx------  1 jorgebarreto1  staff    5885 10 Abr  2007 T2BUTENE.FLD
-rwx------  1 jorgebarreto1  staff   12795 10 Abr  2007 TOLUENE.FLD
-rwx------  1 jorgebarreto1  staff   29459 10 Abr  2007 WATER.FLD
-rwx------  1 jorgebarreto1  staff   15683 10 Abr  2007 XENON.FLD

mixtures:
-rwx------  1 jorgebarreto1  staff  142 10 Abr  2007 AIR.MIX
-rwx------  1 jorgebarreto1  staff  173 10 Abr  2007 R401A.MIX
-rwx------  1 jorgebarreto1  staff  173 10 Abr  2007 R401B.MIX
-rwx------  1 jorgebarreto1  staff  174 10 Abr  2007 R401C.MIX
-rwx------  1 jorgebarreto1  staff  178 10 Abr  2007 R402A.MIX
-rwx------  1 jorgebarreto1  staff  180 10 Abr  2007 R402B.MIX
-rwx------  1 jorgebarreto1  staff  180 10 Abr  2007 R403A.MIX
-rwx------  1 jorgebarreto1  staff  176 10 Abr  2007 R403B.MIX
-rwx------  1 jorgebarreto1  staff  180 10 Abr  2007 R404A.MIX
-rwx------  1 jorgebarreto1  staff  203 10 Abr  2007 R405A.MIX
-rwx------  1 jorgebarreto1  staff  181 10 Abr  2007 R406A.MIX
-rwx------  1 jorgebarreto1  staff  174 10 Abr  2007 R407A.MIX
-rwx------  1 jorgebarreto1  staff  173 10 Abr  2007 R407B.MIX
-rwx------  1 jorgebarreto1  staff  174 10 Abr  2007 R407C.MIX
-rwx------  1 jorgebarreto1  staff  173 10 Abr  2007 R407D.MIX
-rwx------  1 jorgebarreto1  staff  173 10 Abr  2007 R407E.MIX
-rwx------  1 jorgebarreto1  staff  176 10 Abr  2007 R408A.MIX
-rwx------  1 jorgebarreto1  staff  171 10 Abr  2007 R409A.MIX
-rwx------  1 jorgebarreto1  staff  177 10 Abr  2007 R409B.MIX
-rwx------  1 jorgebarreto1  staff  144 10 Abr  2007 R410A.MIX
-rwx------  1 jorgebarreto1  staff  144 10 Abr  2007 R410B.MIX
-rwx------  1 jorgebarreto1  staff  182 10 Abr  2007 R411A.MIX
-rwx------  1 jorgebarreto1  staff  186 10 Abr  2007 R411B.MIX
-rwx------  1 jorgebarreto1  staff  178 10 Abr  2007 R412A.MIX
-rwx------  1 jorgebarreto1  staff  187 10 Abr  2007 R413A.MIX
-rwx------  1 jorgebarreto1  staff  210 10 Abr  2007 R414A.MIX
-rwx------  1 jorgebarreto1  staff  212 10 Abr  2007 R414B.MIX
-rwx------  1 jorgebarreto1  staff  145 10 Abr  2007 R415A.MIX
-rwx------  1 jorgebarreto1  staff  144 10 Abr  2007 R415B.MIX
-rwx------  1 jorgebarreto1  staff  181 10 Abr  2007 R416A.MIX
-rwx------  1 jorgebarreto1  staff  180 10 Abr  2007 R417A.MIX
-rwx------  1 jorgebarreto1  staff  182 10 Abr  2007 R418A.MIX
-rwx------  1 jorgebarreto1  staff  177 10 Abr  2007 R419A.MIX
-rwx------  1 jorgebarreto1  staff  147 10 Abr  2007 R420A.MIX
-rwx------  1 jorgebarreto1  staff  146 10 Abr  2007 R421A.MIX
-rwx------  1 jorgebarreto1  staff  146 10 Abr  2007 R421B.MIX
-rwx------  1 jorgebarreto1  staff  183 10 Abr  2007 R422A.MIX
-rwx------  1 jorgebarreto1  staff  182 10 Abr  2007 R422B.MIX
-rwx------  1 jorgebarreto1  staff  183 10 Abr  2007 R422C.MIX
-rwx------  1 jorgebarreto1  staff  148 10 Abr  2007 R423A.mix
-rwx------  1 jorgebarreto1  staff  253 10 Abr  2007 R424A.MIX
-rwx------  1 jorgebarreto1  staff  180 10 Abr  2007 R425A.mix
-rwx------  1 jorgebarreto1  staff  222 10 Abr  2007 R426A.MIX
-rwx------  1 jorgebarreto1  staff  204 10 Abr  2007 R427A.MIX
-rwx------  1 jorgebarreto1  staff  219 10 Abr  2007 R428A.MIX
-rwx------  1 jorgebarreto1  staff  143 10 Abr  2007 R500.MIX
-rwx------  1 jorgebarreto1  staff  142 10 Abr  2007 R501.MIX
-rwx------  1 jorgebarreto1  staff  141 10 Abr  2007 R502.MIX
-rwx------  1 jorgebarreto1  staff  139 10 Abr  2007 R503.MIX
-rwx------  1 jorgebarreto1  staff  142 10 Abr  2007 R504.MIX
-rwx------  1 jorgebarreto1  staff  145 10 Abr  2007 R507A.MIX
-rwx------  1 jorgebarreto1  staff  143 10 Abr  2007 R508A.MIX
-rwx------  1 jorgebarreto1  staff  143 10 Abr  2007 R508B.MIX
-rwx------  1 jorgebarreto1  staff  144 10 Abr  2007 R509A.MIX
-rwx------  1 jorgebarreto1  staff  179 10 Abr  2007 r422d.mix

fortran:
-rwxrwxrwx  1 jorgebarreto1  staff   53661 10 Abr  2007 CORE_ANC.FOR
-rwxrwxrwx  1 jorgebarreto1  staff   46316 10 Abr  2007 CORE_BWR.FOR
-rwxrwxrwx  1 jorgebarreto1  staff   33201 10 Abr  2007 CORE_CPP.FOR
-rwxrwxrwx  1 jorgebarreto1  staff   10922 10 Abr  2007 CORE_DE.FOR
-rwxrwxrwx  1 jorgebarreto1  staff   25692 10 Abr  2007 CORE_ECS.FOR
-rwxrwxrwx  1 jorgebarreto1  staff   51401 10 Abr  2007 CORE_FEQ.FOR
-rwxrwxrwx  1 jorgebarreto1  staff   30759 10 Abr  2007 CORE_MLT.FOR
-rwxrwxrwx  1 jorgebarreto1  staff   19933 10 Abr  2007 CORE_PH0.FOR
-rwxrwxrwx  1 jorgebarreto1  staff   40532 10 Abr  2007 CORE_PR.FOR
-rwxrwxrwx  1 jorgebarreto1  staff   23772 10 Abr  2007 CORE_STN.FOR
-rwxrwxrwx  1 jorgebarreto1  staff  140339 10 Abr  2007 FLASH2.FOR
-rwxrwxrwx  1 jorgebarreto1  staff  112213 10 Abr  2007 FLSH_SUB.FOR
-rwxrwxrwx  1 jorgebarreto1  staff   18761 10 Abr  2007 IDEALGAS.FOR
-rwxrwxrwx  1 jorgebarreto1  staff   34743 10 Abr  2007 MIX_AGA8.FOR
-rwxrwxrwx  1 jorgebarreto1  staff   82648 10 Abr  2007 MIX_HMX.FOR
-rwxrwxrwx  1 jorgebarreto1  staff   45525 10 Abr  2007 PASS_FTN.FOR
-rwxrwxrwx  1 jorgebarreto1  staff   95475 10 Abr  2007 PROP_SUB.FOR
-rwxrwxrwx  1 jorgebarreto1  staff   10147 10 Abr  2007 REALGAS.FOR
-rwxrwxrwx  1 jorgebarreto1  staff  134021 10 Abr  2007 SAT_SUB.FOR
-rwxrwxrwx  1 jorgebarreto1  staff  110758 10 Abr  2007 SETUP.FOR
-rwxrwxrwx  1 jorgebarreto1  staff   41836 10 Abr  2007 SETUP2.FOR
-rwxrwxrwx  1 jorgebarreto1  staff   47327 10 Abr  2007 TRNSP.FOR
-rwxrwxrwx  1 jorgebarreto1  staff  151627 10 Abr  2007 TRNS_ECS.FOR
-rwxrwxrwx  1 jorgebarreto1  staff  120603 10 Abr  2007 TRNS_TCX.FOR
-rwxrwxrwx  1 jorgebarreto1  staff   84554 10 Abr  2007 TRNS_VIS.FOR
-rwxrwxrwx  1 jorgebarreto1  staff   57074 10 Abr  2007 UTILITY.FOR
-rwxrwxrwx  1 jorgebarreto1  staff   84031 10 Abr  2007 manual.txt

**Comment by speredenn** [comment]
Hi @jaabarreto, you'll need to use v0.2 of this project to get rid of the error. See #22 for reference.

**Comment by jaabarreto** [comment]
Solved, thank you!
