### ISSUE TITLE
Matlab Integration

### ISSUE THREAD

**Issue by jaabarreto** [jowr/librefprop.so#33]
While using the matlab I got this error when I call the test.m file, I'm working on 64 bit MacOSx

Error using loadlibrary (line 440)
Not enough input arguments.
Error in ==>rp_proto64 at 10
There was an error running /opt/refprop/rp_proto64.m.
Run rp_proto64 from the command line to reproduce the error and fix it.

Error in refpropm (line 242)
    [notfound,warnings]=loadlibrary(strcat(BasePath,dllName),prototype,'alias',libName);

Error in test (line 2)
Tp=refpropm('T','C',0,' ',0,'water');

Error in run (line 63)
evalin('caller', [script ';']);

Caused by:
    Error using rp_proto64 (line 10)
    Not enough input arguments.

**Comment by ibell** [comment]
What version of MATLAB?  @jowr is not available for a while - perhaps I can
help you.

**Comment by jaabarreto** [comment]
R2014b

**Comment by ibell** [comment]
What is in line 10 of rp_proto64?  I don't have access to this system
configuration to test on my side.

**Comment by jaabarreto** [comment]
ThunkLibName=fullfile(basePath,'librefprop_thunk_maci64');

**Comment by ibell** [comment]
Do you have that file (librefprop_thunk_maci64) somewhere on your computer?

**Comment by jaabarreto** [comment]
Yes, I have the .dylib file

**Comment by ibell** [comment]
Where is that dylib file located?

**Comment by ibell** [comment]
Also, can you please run:

otool -L /path/to/dylib

and report the output?

**Comment by jaabarreto** [comment]
At /opt/refprop

Jorge André Barreto
jorgeandrebarreto@gmail.com

No dia 28/08/2015, às 18:46, Ian Bell <notifications@github.com> escreveu:

**Comment by ibell** [comment]
Can you please email me your rp_proto64 to ian.bell@nist.gov?

**Comment by jaabarreto** [comment]
yes.

**Comment by jaabarreto** [comment]
Which directory I have to run the 'otool -L /path/to/dylib'?

**Comment by ibell** [comment]
How about this: otool -L /opt/refprop/librefprop.so ?

**Comment by jaabarreto** [comment]
/opt/refprop/librefprop.dylib:
	/home/jorgebarreto1/lib/librefprop.9.1.dylib (compatibility version 9.1.0, current version 9.1.0)
	/usr/local/lib/gcc/5/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)

**Comment by ibell** [comment]
Hmm... that all seems ok as far as I see...

**Comment by jaabarreto** [comment]
Problem solved, I had to change some directories rproto and refprop.m and placed all the files on HOME/Documents/matlab...even with the dylib file (soft link) and the thunk.dylib
