### ISSUE TITLE
Anaconda

### ISSUE THREAD

**Issue by bo3mrh** [jowr/librefprop.so#34]
Hello,

I had REFPROP 9.0 working in CoolProp perfectly before I installed Anaconda to update CoolProp to v5.1.1.
The problem now is the compiler stops when it reaches any line calls REFPROP.
Any one can help me this matter ?

I'm using OSX 10.10.5
librefprop v0.2
Eclipse Lunar 4.4.2

**Comment by ibell** [comment]
? When you say compiler, do you mean python? Or is it really the
compilation that is failing?  I'm on 10.10 and it compiled ok for me.
Error log?

**Comment by bo3mrh** [comment]
Hello Ian,
I meant that the compilation stopped. No error messages.
I tried to change the directory in the MAKE file and reinstall it, but nothing happened.
Did you use v0.2 ?

**Comment by ibell** [comment]
What version of REFPROP do you use?

**Comment by bo3mrh** [comment]
V9.0

**Comment by bo3mrh** [comment]
Ok. When I tried to run through Terminal I got the following message:

`Segmentation fault: 11`

**Comment by bo3mrh** [comment]
Update:
I tried to `make uninstall` and reinstall libreprop again. I managed to get the following error message:

```
Good news: It is possible to use REFPROP on your system! However, the library 
could not be loaded. Please make sure that REFPROP is available on your system.

Neither found in current location nor found in system PATH.
If you already obtained a copy of REFPROP from http://www.nist.gov/srd/, 
add location of REFPROP to the PATH environment variable or your library path.

In case you do not use Windows, have a look at https://github.com/jowr/librefprop.so 
to find instructions on how to compile your own version of the REFPROP library.


Traceback (most recent call last):
  File "/Users/ammarbahman/Desktop/Test/PathCheck.py", line 70, in <module>
    print 'Temp of Water at 101.325 kPa is: ',CoolProp.CoolProp.PropsSI('T','P',101325,'Q',0,'REFPROP::Water'), 'K'
  File "CoolProp/CoolProp.pyx", line 216, in CoolProp.CoolProp.PropsSI (CoolProp/CoolProp.cpp:25933)
  File "CoolProp/CoolProp.pyx", line 296, in CoolProp.CoolProp.PropsSI (CoolProp/CoolProp.cpp:25734)
  File "CoolProp/CoolProp.pyx", line 185, in CoolProp.CoolProp.__Props_err2 (CoolProp/CoolProp.cpp:24059)
ValueError: Initialize failed for backend: "REFPROP", fluid: "Water" fractions "[ 1.0000000000 ]"; error: You cannot use the REFPROPMixtureBackend. : PropsSI("T","P",101325,"Q",0,"REFPROP::Water")
```

**Comment by bo3mrh** [comment]
Update:
While playing around, I figured out that when I switched back the Python interpreter (in Eclipse) to the original directory (/usr/bin/python), everything works fine!
<img width="791" alt="screen shot 2015-09-24 at 23 37 14" src="https://cloud.githubusercontent.com/assets/11583412/10092537/84985f1a-6315-11e5-95fd-466832a8928b.png">

**Comment by ibell** [comment]
Maybe one is 32bit and the other is 64 bit?  Though that doesn't make a lot
of sense on osx 10.10, where both should be 64 but

**Comment by ibell** [comment]
Probably an issue with something in eclipse.  Path setup or something.
Make sure the script runs outside of eclipse with both python versions

**Comment by bo3mrh** [comment]
Well, both directories have the latest python version.
Does the version of CoolProp has anything to do with it? (`/usr/bin/python` has CoolProp v5.0.8)
<img width="932" alt="screen shot 2015-09-24 at 23 50 01" src="https://cloud.githubusercontent.com/assets/11583412/10092676/21c8d5b6-6317-11e5-907c-787f861c9a9e.png">

**Comment by ibell** [comment]
It shouldn't.  I use the anaconda python with up to date CoolProp

**Comment by bo3mrh** [comment]
Could it be that I had the REFPROP files in the wrong directory path!? Could you please tell me which line should I change in MAKEFILE of librefprop (since I'm having REFPROP v9.0, I'm using librefprop v0.2)

**Comment by speredenn** [comment]
It may be an environment definition problem, maybe. Is the REFPROP binary found, to start with, from inside the anaconda environment?

**Comment by bo3mrh** [comment]
Speredenn,
Yes, it is. It is a segmentation error because I have REFPROP v9.0 and need to update to v9.1. I found it out here (no.2 ): https://github.com/CoolProp/CoolProp/blob/master/FAQ.md
I noticed that CoolProp v5.0.8 still work fine with REFPROPv9.0, but v5.1.1 does not.
I think there is no other way but to update to v9.1. what do you think ?

**Comment by speredenn** [comment]
@bo3mrh: @ibell is the best guy around there to tell you if there is a way or not - noboby knows CoolProp internals better than he does ;-). IMO, there is no other way, however.

**Comment by speredenn** [comment]
@bo3mrh: @ibell is the best guy around there to tell you if there is a way or not - noboby knows CoolProp internals better than he does ;-). IMO, there is no other way, however.

**Comment by speredenn** [comment]
@bo3mrh: @ibell is the best guy around there to tell you if there is a way or not - noboby knows CoolProp internals better than he does ;-). IMO, there is no other way, however.

**Comment by speredenn** [comment]
@bo3mrh: @ibell is the best guy around there to tell you if there is a way or not - noboby knows CoolProp internals better than he does ;-). IMO, there is no other way, however.
