### ISSUE TITLE
ref prop 2310 compile error

### ISSUE THREAD

**Issue by jeffkenvin** [jowr/librefprop.so#42]
I receive the following error when running make with the v10 of refprop.

ld: 77 duplicate symbols for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [bin/librefprop.dylib] Error 1

I have the most current gcc and gfortran (and Xtools command line tools) installed.

Any thoughts on what needs to be changed?
thanks

**Comment by ianhbell** [comment]
Can you use : https://github.com/usnistgov/REFPROP-cmake ?  That's the recommendation nowadays for REFPROP 10, works reliably for most users.

**Comment by jeffkenvin** [comment]
It fails with the following output:

Jeffreys-MacBook-Pro:build jeffreykenvin$ cmake .. -DCMAKE_BUILD_TYPE=Release
-- DEFSYM_FLAG: 
-- darwin
Traceback (most recent call last):
  File "/Users/jeffreykenvin/REFPROP_cmake/generate_aliases.py", line 129, in <module>
    tokens = tokenize(header_path, FORTRAN_path)
  File "/Users/jeffreykenvin/REFPROP_cmake/generate_aliases.py", line 28, in tokenize
    with open(path_to_REFPROP_lib_h, 'r') as fp:
IOError: [Errno 2] No such file or directory: '/Users/jeffreykenvin/REFPROP_cmake/externals/REFPROP-headers/REFPROP_lib.h'

CMake Error at CMakeLists.txt:148 (file):
  file failed to open for reading (No such file or directory):

    /Users/jeffreykenvin/REFPROP_cmake/build/aliases_string.txt


-- Path to libquadmath.a:/usr/local/Cellar/gcc/8.3.0/lib/gcc/8/gcc/x86_64-apple-darwin18.2.0/8.3.0/../../../libquadmath.a
-- Copied libquadmath.a here.
-- Configuring incomplete, errors occurred!
See also "/Users/jeffreykenvin/REFPROP_cmake/build/CMakeFiles/CMakeOutput.log".

**Comment by ianhbell** [comment]
You needed to do a recursive clone, should be fine if you fix that.

**Comment by jeffkenvin** [comment]
Thank-you the recursive clone worked well and I missed that instruction in the readme.

I also discovered the upgrade to v10 left old versions (v8) of the fortran files and this caused some compile errors.  Once I removed the old versions it compiled without any problems.

**Comment by jowr** [comment]
Hi, happy to hear that everything works now. I guess I can retire this repository to avoid confusion in the future...
